### ISSUE TITLE
Failed to build module 'Accelerate'; this SDK is not supported by the compiler

### ISSUE THREAD

**Issue by ankitpanchotiya99138** [onevcat/Kingfisher#1725]
Hello,
Can any one help me I have face issue on Accelerate. I user Latest xcode 13 beta.

Failed to build module 'Accelerate'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.17.216 clang-1300.0.18.1)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.19.104 clang-1300.0.18.4)'). Please select a toolchain which matches the SDK.

![Screenshot 2021-06-12 at 8 53 54 AM](https://user-images.githubusercontent.com/48627319/121763693-b8556a00-cb5b-11eb-93d9-ab6df2054c89.png)

**Comment by onevcat** [comment]
I believe it is a bug in the beta version of Xcode. Some less-used system frameworks were built with a different compiler and bundled in this version (there are Accelerate, Network and more).

I suggest waiting for the next beta two weeks later.

**Comment by ankitpanchotiya99138** [comment]
Ok Thanks for the quick response.

**Comment by aleemtoor** [comment]
Duplicated with #1736

**Comment by grantespo** [comment]
so just gotta wait for Xcode to fix kk, any day they should have update...

**Comment by vd-ba** [comment]
Looks like there is similar issue with Xcode 13 Beta 2, albeit with different swift compiler version:

`Local setup: ❌  /Users/********/Library/Developer/Xcode/DerivedData/MyApp-drgvolpecatijzcuichjljjshvoi/SourcePackages/checkouts/Kingfisher/Sources/Image/ImageDrawing.swift:27:8: failed to build module 'Accelerate'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.20.4 clang-1300.0.21.1)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.20.104 clang-1300.0.21.1)'). Please select a toolchain which matches the SDK.`

**Comment by onevcat** [comment]
This seems only happens for SPM and it requires a minimum target iOS 12 to build successfully. I don't think this is reasonable and it is definitely an issue of the build system (unless Apple officially confirms they want to drop any deploy target below iOS 12)


I updated the package file in the master branch. So if you already have a deploy target equal or above iOS 12, you can switch to the master branch now to archive your project. However, I still suggest wait for another beta to see how it can change. (As far as I can say, beta 2 shipped with the same compiler version and build system as in beta 1, so it is not surprising the same thing happens.)

**Comment by vd-ba** [comment]
> This seems only happens for SPM and it requires a minimum target iOS 12 to build successfully. I don't think this is reasonable and it is definitely an issue of the build system (unless Apple officially confirms they want to drop any deploy target below iOS 12)
> 
> I updated the package file in the `fix/xcode-13` branch. So if you already have a deploy target equal or above iOS 12, you can switch to the master branch now to archive your project. However, I still suggest wait for another beta to see how it can change. (As far as I can say, beta 2 shipped with the same build system as in beta 1, so it is not surprising the same thing happens.)
> 
> I will see if we really need to drop any early versions before iOS 12 and decide to merge the `fix/xcode-13` to master in the future.
> 
> Ref commit: [f012224](https://github.com/onevcat/Kingfisher/commit/f012224344f09421588a28e9f6259968e3574f8b)

Thanks, works fine 👍. Will do for now, hopefull Apple will get it fixed.

**Comment by Andrewangeta** [comment]
This resolved with Beta 3?

**Comment by linsyorozuya** [comment]
> This resolved with Beta 3?

NO...

**Comment by Andrewangeta** [comment]
I just tried it and it worked

**Comment by onevcat** [comment]
I can confirm a similar issue is still happening in Xcode 13 beta 3 when archiving a project. 

However, it is now complaining about Combine instead of the original Accelerate. It seems that Apple is now building Accelerate with the same compiler, but not Combine yet.

There is some progress and I need to keep looking on it. If at last we cannot have a stable situation, we have to upgrade the deploy target in the SPM from `.v10` to `.v12` to make compiler happy.

**Comment by onevcat** [comment]
This is marked as a known issue in Xcode 13 beta 5 release note:

> Swift libraries may fail to build for iOS targets that use armv7. (74120874)
> Workaround: Increase the platform dependency of the package to v12 or later.

So I believe Apple would fix it later in a release version. Let me see...

**Comment by onevcat** [comment]
There is no way for now to support it since it is an Apple issue. Even though, I guess it is very little meaning to continue support iOS 10 and 11 since they are only 0.5% share in total. But let's see how the next Xcode can work, which is the pre-condition.

![截屏2021-08-28 10 52 59](https://user-images.githubusercontent.com/1019875/131202548-0a44a1b1-3f1e-41c5-bd5b-455d6e7cdf8f.png)

**Comment by rursache** [comment]
still happening on Xcode 13 GM

**Comment by onevcat** [comment]
> This is marked as a known issue in Xcode 13 beta 5 release note:
> > Swift libraries may fail to build for iOS targets that use armv7. (74120874)
> > Workaround: Increase the platform dependency of the package to v12 or later.
>
> So I believe Apple would fix it later in a release version. Let me see...

At least this known issue is still there in Xcode 13 RC today. So I guess it is just an official announcement of "Dropping iOS 11 and below" to us library maintainers. Kingfisher v7 (currently in beta) is already setting its deploy target to iOS 12. If anyone needs it, please check the [migration guide](https://github.com/onevcat/Kingfisher/wiki/Kingfisher-7.0-Migration-Guide).

**Comment by richieWave** [comment]
Xcode 13 it's out now. Will v7 be available soon?

**Comment by BrunoCerberus** [comment]
Same problem here with public version of Xcode 13

**Comment by onevcat** [comment]
I am going with some final check and will tag v7 soon.

**Comment by onevcat** [comment]
It is not a thing can be fixed in Kingfisher. See https://github.com/onevcat/Kingfisher/issues/1802#issuecomment-919815919

There are basically two choice:

1. If you do not need to support iOS 11 and below, upgrade to Kingfisher v7 then you can use it with Xcode 13.
2. Or, if unfortunately you still need to work for iOS 10 or 11, you have to keep using Kingfisher v6 and Xcode 12.x for a while, and pray that Apple will fix it in Xcode 13.1 or later.

**Comment by fullc0de** [comment]
Hello, @onevcat  
I sincerely appreciate your efforts to cover all issues from Xcode 13. 

I found the branches, `release/version6` and `fix/xcode-13`, and those separated branches aren't helpful for someone using v6 with the minimum target at least under ios13 and struggling with the Xcode issue. 

If you pick `fix/xcode-13`, you can't resolve the `loadImmediately` issue.
If you pick `release/version6`, you are still in trouble with the Xcode 13 issue.

I'd like to suggest you bring back `loadImmediately` method to the `release/version6` if you regard this branch to be used as the latest v6.

**Comment by Gavin123** [comment]
Xcode13 public version is also same problem

**Comment by huangMingHua** [comment]
> still happening on Xcode 13 GM
> 
> running works, archiving outputs this crap:
> ![trying to archive](https://camo.githubusercontent.com/2335d5a82536324eefca93157bdaed2cd7b5a2b61eb853ec970090c6bb26e978/68747470733a2f2f692e696d6775722e636f6d2f4c746d6a35454d2e6a7067)
my project using Kingfisher by cocoapods  and need to support iOS 10, i occurred the some error,
in my project i don't using swiftui, i fix this error in ruby script.
`Podfile`
```
platform :ios, '10.0'
use_modular_headers!
inhibit_all_warnings!
...
pre_install do |installer|
    remove_swiftui()
end

def remove_swiftui
  # 解决 xcode13 Release模式下SwiftUI报错问题
  system("rm -rf ./Pods/Kingfisher/Sources/SwiftUI")
  code_file = "./Pods/Kingfisher/Sources/General/KFOptionsSetter.swift"
  code_text = File.read(code_file)
  code_text.gsub!(/#if canImport\(SwiftUI\) \&\& canImport\(Combine\)(.|\n)+#endif/,'')
  system("rm -rf " + code_file)
  aFile = File.new(code_file, 'w+')
  aFile.syswrite(code_text)
  aFile.close()
end
```
i hope i can help you.

**Comment by pangyunxiu** [comment]
> use_modular_headers!

你好，我直接复制粘贴你的东西，我把你的东西放在target '项目名' do ... end ，也解决不了啊？？？需要怎么弄？？？？

**Comment by huangMingHua** [comment]
@pangyunxiu 
你的描述比较模糊，不清楚你遇到的是否和我一样的问题，我试了下放在`target 'xxx' do  ... end` 里面也是仍然起效的。

**Comment by Tliens** [comment]
> > still happening on Xcode 13 GM
> > running works, archiving outputs this crap:
> > ![trying to archive](https://camo.githubusercontent.com/2335d5a82536324eefca93157bdaed2cd7b5a2b61eb853ec970090c6bb26e978/68747470733a2f2f692e696d6775722e636f6d2f4c746d6a35454d2e6a7067)
> 
> my project using Kingfisher by cocoapods and need to support iOS 10, i occurred the some error, in my project i don't using swiftui, i fix this error in ruby script. `Podfile`
> 
> ```
> platform :ios, '10.0'
> use_modular_headers!
> inhibit_all_warnings!
> ...
> pre_install do |installer|
>     remove_swiftui()
> end
> 
> def remove_swiftui
>   # 解决 xcode13 Release模式下SwiftUI报错问题
>   system("rm -rf ./Pods/Kingfisher/Sources/SwiftUI")
>   code_file = "./Pods/Kingfisher/Sources/General/KFOptionsSetter.swift"
>   code_text = File.read(code_file)
>   code_text.gsub!(/#if canImport\(SwiftUI\) \&\& canImport\(Combine\)(.|\n)+#endif/,'')
>   system("rm -rf " + code_file)
>   aFile = File.new(code_file, 'w+')
>   aFile.syswrite(code_text)
>   aFile.close()
> end
> ```
> 
> i hope i can help you.

确实可以

**Comment by arthurchenjs** [comment]
问题的关键是armv7不支持，而不是iOS 10 系统的问题
所以应该是设置只编译arm64架构即可
毕竟都2021年了，arm64从iphone5s开始，你想支持iPhone5估计也没有用户了。

所以用以下方式可以，解决编译问题，
并支持version 6，xcode 13，iOS 10+，不用删除swiftUI，不用升级iOS target

解决方法1 ：参见 pr 1853
https://github.com/onevcat/Kingfisher/pull/1853

解决方法2 ：若不更新podspec ,可本地更新
` 
post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "Kingfisher"
        config.build_settings['EXCLUDED_ARCHS'] = "armv7"
      end                  
    end
  end
end
`
若generate_multiple_pod_projects: true 时，获取 target用如下方式
installer_representation.pod_target_subprojects.flat_map { |p| p.targets }.each do |target|

**Comment by GentleForYou** [comment]
> 

太感谢了，苹果真心坑啊，哎
