### ISSUE TITLE
Loading indicator disappears randomly.

### ISSUE THREAD

**Issue by hifall** [onevcat/Kingfisher#447]
I found the loading indicator can disappear sometimes in such a scenario, but I have not found a consistent repro yet.

This happens in a table view with some chat messages.
1 fill the table view with about a dozen messages;
2 inert an image message whose image is managed by Kingfisher by calling:
            imageView?.kf_showIndicatorWhenLoading = true
            imageView?.kf_indicatorType = .Activity
            imageView?.kf_setImageWithURL(...) with a placeholder image;
now the loading indicator shows up;
3 while the image is being loaded, scroll it out of the view port of the table, so that the image is not visible;
4 scroll the image back into the view port to make it visible; now the loading indicator could be missing even when the image is still being loaded.

**Comment by onevcat** [comment]
Will take a look at it soon.

**Comment by onevcat** [comment]
@hifall Hi, 

After some investigation, I believe there is no issue in Kingfisher's loading indicator behaviors.

The issue you encountered might be related to the changes on collection view/table view in iOS 10. If you are calling Kingfisher's `cancelDownloadTask` in `didEndDisplaying` delegate method and resetting the image in `collectionView(:cellForItemAt:)`, you may suffer this. Since in iOS 10, Apple is using a more aggressive cache way on cells. Now they will not be in reuse queue at the time it goes out of screen, the resetting method may not be called. So the indicator will not show again.

You could try to put your set image code to `collectionView(:willDisplay:forItemAt:)` instead, to make sure the image is being reloaded and set correctly for that cell.

**Comment by onevcat** [comment]
You could find more about this change in iOS in [session 219](https://developer.apple.com/videos/play/wwdc2016/219/)

**Comment by onevcat** [comment]
Some sample code added in #448 to show how to get performance benefit from iOS 10's prefetching cell and new cell life cycle.

**Comment by hifall** [comment]
Okay -- thanks for the heads-up. But the issue happened in iOS 9.3.5, instead of 10. Not sure enough at the moment what's going on, yet.

I will take a deeper look into this later.

**Comment by hifall** [comment]
So, I did try a few more times on iOS 9.3.5., and I saw the issue again. Although I did not dig through the source code to find the problem.

**Comment by Codeido** [comment]
I have the same problem, before Xcode 8 and the transition to swift 2.3, the activity indicator worked properly on all my collectionViews. Now it doesn't work.

**Comment by onevcat** [comment]
@Codeido I can not reproduce this issue on my environment (I tried both iOS 9 and 10).

Can you build a sample project for this? So I can dig into it deeper.

**Comment by Codeido** [comment]
@onevcat you used swift 2.3?

**Comment by onevcat** [comment]
Yes, I tried swift2.3 branch and cannot reproduce it.

But I did find a bug which might stop you from setting the `kf_showIndicatorWhenLoading` to `false`, but it should not relate to this issue, if you are only setting it to `true`.

**Comment by Codeido** [comment]
I fixed it on swift 2.3 and iOS 10 calling kf_showIndicatorWhenLoading=true before the method kf_setImageWithURL 👍  :|

**Comment by onevcat** [comment]
@Codeido So may I know what's your original code? Maybe it could be improved.

**Comment by Codeido** [comment]
Yeah @onevcat !

My original code was: 

```
cell.imageProduct.kf_setImageWithURL(NSURL(string: variantSelected!.gallery![indexPath.item] ?? ""),
                                             placeholderImage: nil,
                                             optionsInfo: [.Transition(ImageTransition.Fade(0.5)), .ForceTransition])
cell.imageProduct.kf_showIndicatorWhenLoading = true
```

now is:

```
cell.imageProduct.kf_showIndicatorWhenLoading = true
cell.imageProduct.kf_setImageWithURL(NSURL(string: variantSelected!.gallery![indexPath.item] ?? ""),
                                             placeholderImage: nil,
                                             optionsInfo: [.Transition(ImageTransition.Fade(0.5)), .ForceTransition])
```

**Comment by hifall** [comment]
@Codeido,

I don't see much difference between your code and what I posted at top, except that you pass in non-nil optionsInfo. I tried yours, but the problem stays.

**Comment by hifall** [comment]
@onevcat,

Regarding your comment: "But I did find a bug which might stop you from setting the kf_showIndicatorWhenLoading to false, but it should not relate to this issue, if you are only setting it to true.", this is what it's like in our scenario: we have 2 types of images managed using Kingfisher, one that displays a loading indicator when the image is being loaded, and the other one that displays NO loading indicator. So indeed, kf_showIndicatorWhenLoading can be set to false in our case -- could that cause the images that are supposed to display a loading indicator to actually fail to do so?

**Comment by hifall** [comment]
@onevcat,

This issue happens around 50% chance on my device. So once you have a fix for the kf_showIndicatorWhenLoading issue you mentioned, maybe I can give it a test here.

**Comment by onevcat** [comment]
@Codeido That's true, you need to set the loading indicator before you begin loading an image.

@hifall I pushed a commit for it in swift2.3 branch. Would you like to give it a try?

**Comment by hifall** [comment]
Cool. Trying that now...

**Comment by hifall** [comment]
@onevcat,

I am not seeing any new commit from last few hours in swift2.3 branch. Am I missing something here?

**Comment by onevcat** [comment]
It should be there.

https://github.com/onevcat/Kingfisher/commit/c20e4556e84326e47e7e8081ea6903b2c2c00a39

I made the change earlier, just didn't push it until now.

**Comment by hifall** [comment]
Thanks @onevcat.

I have tested your fix. But the problem still shows.

**Comment by onevcat** [comment]
@hifall Ummm, checked the code again and not sure about why.

Are you trying to set the indicator and/or image in another thread instead of main thread?

**Comment by onevcat** [comment]
Or if there is a demo could reproduce it, I'd like to dig it deeper. Currently I cannot reproduce it so it's quite hard to debug.

**Comment by onevcat** [comment]
@hifall Hi, any progress for this?

**Comment by hifall** [comment]
@onevcat,

I have not been able to find time to isolate this issue in a reasonably small project. I will get back to you when I can.
