### ISSUE TITLE
Library not loaded: @rpath/libswiftAccelerate.dylib

### ISSUE THREAD

**Issue by Dschee** [onevcat/Kingfisher#903]
#### What

When including Kingfisher using latest Carthage in a project which has subprojects as components, when running one of the subprojects tests we get the following error:

```
2018-04-17 14:14:03.494908+0200 xctest[8052:65955] The bundle “MyProjectUITests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2018-04-17 14:14:03.495059+0200 xctest[8052:65955] (dlopen_preflight(/Users/Me/Library/Developer/Xcode/DerivedData/MyProjectiOS-cmerazywlpjaaidjguatkfroiqih/Build/Products/Debug-iphonesimulator/MyProjectUITests.xctest/FitterYouUITests): Library not loaded: @rpath/libswiftAccelerate.dylib
  Referenced from: /Users/Me/Code/Apple/MyProject/Carthage/Build/iOS/Kingfisher.framework/Kingfisher
  Reason: image not found)
Program ended with exit code: 82
```

#### Other Comment

As you can see it seems there's an issue with the `Accellerate` framework which is included. I'm guessing that since the dependency isn't placed directly into the component project, Xcode has problems including the implicit dependency without explicitly stating where it is. The usual search paths (I know about @loader_path and @rpaths – already tried those approaches to fix this) seem not to be enough.

**Comment by Dschee** [comment]
I tried everything [here](https://stackoverflow.com/questions/32771796/dyld-library-not-loaded-rpath-libswiftavfoundation-dylib) and [there](https://stackoverflow.com/questions/26024100/dyld-library-not-loaded-rpath-libswiftcore-dylib/33153733) without success. :(

**Comment by onevcat** [comment]
@Dschee Not sure what could cause it, but it is more likely an issue that the test bundle (target) does not contain `libswiftAccelerate.dylib`. Maybe it worth to try to enable `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` in the Info.plist of your UI test target too?

**Comment by Dschee** [comment]
Already tried that. Found a workaround: Using HanekeSwift instead of Kingfisher. ;)

**Comment by onevcat** [comment]
Great!

**Comment by Dschee** [comment]
Sorry for being rude, shouldn't have made a joke about it, was disrespectful. Thank you for taking the time to help me. 🙇

**Comment by Dschee** [comment]
Ah, ok, then I overknterpreted things. Anyways, was rude. ^^

By the way, the project structure where I integrated this os weird, too. If I were you I‘d keep in the back of my mind that there was such an issue bbt won‘t do anything about it unless someone else would run into similar problems. But it‘s weird in any case ...

**Comment by onevcat** [comment]
Sure. Maybe you were importing or using Kingfisher’s method in the UI test target, which did not make sense and should not happen in fact. I would try to see whether I can reproduce it later, but if I cannot, I will just let it go.

Thanks!

**Comment by radugrinico** [comment]
Hello @onevcat.

 I have the same issue. 
```The bundle “Tests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2018-04-26 21:37:14.897881+0200 xctest[12206:269444] (dlopen_preflight(/Tests.xctest/Tests): Library not loaded: @rpath/libswiftAccelerate.dylib
  Referenced from: /Kingfisher.framework/Kingfisher
  Reason: image not found)```

Any ideas on how to fix it?

**Comment by radugrinico** [comment]
Solved by importing accelerate in the header file of the networking framework where kf is imported as well:
```
#import <Accelerate/Accelerate.h>
```

**Comment by GWesley** [comment]
Try clean build folder

**Comment by Drusy** [comment]
@GWesley clean build folder made it work for me, I don't think this is related to Kingfisher

**Comment by puelocesar** [comment]
Adding the imports didn't worked for me, neither cleaning build folder. Not even adding Accelerate.framework to the "Link Binary with Libraries" phase

Any other ideas?

**Comment by puelocesar** [comment]
Ok, now this is crazy. I tried everything on Friday and I always got the same error, now after a nice weekend visiting the mountains in Austria, I arrived at work and everything just works without doing anything else?

Problem is, I can't tell why it works now. Maybe you just need to visit the Alps?

**Comment by puelocesar** [comment]
One alternative is to fork Kingfisher and remove everything related to Accelerate. It's basically just removing the "blur" feature anyway, so I think it won't be an issue for anybody

**Comment by muukii** [comment]
I fixed this with adding `import Accelerate` to some swift files in test scheme.

**Comment by bill350** [comment]
@muukii The same here. I've removed `Kingfisher` to `AlamofireImage`. 
I think we have to create sub-spec for advanced filtering image effect. It will avoid specific linking of unused framework imports too.

**Comment by MSavisko** [comment]
@gal-orlanczyk 
You could add a new empty target (as single view application), add Accelerate framework (General - Linked Frameworks and Libraries) and define "Host Application" as just added target.

Inspired by:
https://stackoverflow.com/a/42424793

**Comment by wangdu1005** [comment]
@onevcat Still not working by your solution. Build setting didn't have linked binary section.
